stages:
  download:
    cmd: stages/01_download.sh
    deps:
      - stages/01_download.sh
    outs:
      - download
  unzip: 
    cmd: stages/02_unzip.sh
    deps:
      - stages/02_unzip.sh
      - download
    outs:
      - raw
  build: 
    cmd: python stages/03_build.py
    deps:
      - stages/03_build.py
      - raw
    outs:
      - brick
